enum Genre {
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  BIOGRAPHY = 'BIOGRAPHY',
  CRIME = 'CRIME',
  DOCUMENTARY = 'DOCUMENTARY',
  FANTASY = 'FANTASY',
  HISTORY = 'HISTORY',
  MUSIC = 'MUSIC',
  MYSTERY = 'MYSTERY',
  SCIFI = 'SCIFI',
  UNKNOWN = 'UNKNOWN',
}

export default Genre
